title:              GasBag
email:              79104644594@ya.ru
description:        A Blog about NFT by Andrei Dei
author:             Andrei Dei
baseurl:
url:                gasbag.ga

# Social Profiles
twitter_username:
github_username:    Indexmod
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           2
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
